services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8592:8592"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8593:8593"

