###
POST {{BACKEND_URL}}/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Client Test",
    "color": "#FF0000"
}

###
GET {{BACKEND_URL}}/clients HTTP/1.1
Content-Type: application/json

###
PUT {{BACKEND_URL}}/clients/DE1kVd81k87mbps14P7u HTTP/1.1
Content-Type: application/json

{
    "observations": "Observations updated"
}